## Every ID the code refers to by name, as `StringName`.
##
## `StringName` rather than `String` because these are compared on the hot path —
## every score append, every ability lookup, every state transition — and
## `StringName` comparison is pointer-equal and allocation-free.
##
## GENERATED FROM THE CORPUS, then committed. `test_ids_match_glossary.gd`
## asserts the two still agree in both directions: an ID here but not in the
## docs is undocumented, and one in the docs but not here is a name nobody
## implemented. Neither is allowed to persist.
##
## IDs ARE IMMUTABLE ONCE MERGED (`docs/30_bible/NAMING_AND_IDS.md` §2). A wrong
## name is deprecated with a note and a new one added. It is never renamed and
## never reused — a rename fails silently in archived telemetry, in `.tres`
## files and in test names that keep passing while testing the wrong thing.
class_name Ids
extends RefCounted

# --- SCORE ---------------------------------------------------------------
## Score event kinds. The ScoreEvent log is keyed on these.
const SCORE_BLENDED := &"SCORE-BLENDED"
const SCORE_CONTRACT := &"SCORE-CONTRACT"
const SCORE_DEATH := &"SCORE-DEATH"
const SCORE_FOCUS := &"SCORE-FOCUS"
const SCORE_FROMABOVE := &"SCORE-FROMABOVE"
const SCORE_LONGHUNT := &"SCORE-LONGHUNT"
const SCORE_MASKED := &"SCORE-MASKED"
const SCORE_PATIENT := &"SCORE-PATIENT"
const SCORE_POISONED := &"SCORE-POISONED"
const SCORE_RECKLESS := &"SCORE-RECKLESS"
const SCORE_SILENT := &"SCORE-SILENT"
const SCORE_STUN := &"SCORE-STUN"
const SCORE_VARIETY := &"SCORE-VARIETY"
const SCORE_VENDETTA := &"SCORE-VENDETTA"

# --- ABIL ----------------------------------------------------------------
## Abilities.
const ABIL_CINDERFALL := &"ABIL-CINDERFALL"
const ABIL_LUNGE := &"ABIL-LUNGE"
const ABIL_NIGHTSHADE := &"ABIL-NIGHTSHADE"
const ABIL_SECONDFACE := &"ABIL-SECONDFACE"
const ABIL_WHISPERBOLT := &"ABIL-WHISPERBOLT"

# --- PASV ----------------------------------------------------------------
## Passives.
const PASV_COLDREAD := &"PASV-COLDREAD"
const PASV_SECONDWIND := &"PASV-SECONDWIND"
const PASV_STILLNESS := &"PASV-STILLNESS"

# --- PERSONA -------------------------------------------------------------
## Playable personas. A persona is also a clone roster.
const PERSONA_CANTATRICE := &"PERSONA-CANTATRICE"
const PERSONA_LUCERNA := &"PERSONA-LUCERNA"
const PERSONA_PESATORE := &"PERSONA-PESATORE"
const PERSONA_VETRAIO := &"PERSONA-VETRAIO"

# --- ARCH ----------------------------------------------------------------
## NPC filler archetypes.
const ARCH_CHILD := &"ARCH-CHILD"
const ARCH_FISHWIFE := &"ARCH-FISHWIFE"
const ARCH_MENDICANT := &"ARCH-MENDICANT"
const ARCH_PORTER := &"ARCH-PORTER"
const ARCH_WATERCARRIER := &"ARCH-WATERCARRIER"

# --- MAP -----------------------------------------------------------------
## Maps.
const MAP_VETRAIO := &"MAP-VETRAIO"

# --- EVT -----------------------------------------------------------------
## Event-bus signals. Presentation only — systems call directly.
const EVT_ABILITY_COOLDOWN_CHANGED := &"EVT-ABILITY-COOLDOWN-CHANGED"
const EVT_ABILITY_DENIED := &"EVT-ABILITY-DENIED"
const EVT_ABILITY_STARTED := &"EVT-ABILITY-STARTED"
const EVT_BLEND_STATE_CHANGED := &"EVT-BLEND-STATE-CHANGED"
const EVT_CAPTION := &"EVT-CAPTION"
const EVT_COMPASS_PULSED := &"EVT-COMPASS-PULSED"
const EVT_COMPASS_UPDATED := &"EVT-COMPASS-UPDATED"
const EVT_CONNECTION_CHANGED := &"EVT-CONNECTION-CHANGED"
const EVT_CONTRACT_ASSIGNED := &"EVT-CONTRACT-ASSIGNED"
const EVT_CONTRACT_PORTRAIT_REVEALED := &"EVT-CONTRACT-PORTRAIT-REVEALED"
const EVT_KILL_READY_CHANGED := &"EVT-KILL-READY-CHANGED"
const EVT_KILL_RESOLVED := &"EVT-KILL-RESOLVED"
const EVT_MATCH_PHASE_CHANGED := &"EVT-MATCH-PHASE-CHANGED"
const EVT_PREY_WARNING_TRIGGERED := &"EVT-PREY-WARNING-TRIGGERED"
const EVT_SCORE_EVENT_APPENDED := &"EVT-SCORE-EVENT-APPENDED"
const EVT_STUN_RESOLVED := &"EVT-STUN-RESOLVED"
const EVT_SUSPICION_TIER_CHANGED := &"EVT-SUSPICION-TIER-CHANGED"
const EVT_SUSPICION_VALUE_CHANGED := &"EVT-SUSPICION-VALUE-CHANGED"
const EVT_TUNING_RELOADED := &"EVT-TUNING-RELOADED"

# --- NET -----------------------------------------------------------------
## Network messages. C2S is a request; S2C is a fact.
const NET_C2S_ABILITY_REQUEST := &"NET-C2S-ABILITY-REQUEST"
const NET_C2S_BLEND_REQUEST := &"NET-C2S-BLEND-REQUEST"
const NET_C2S_HELLO := &"NET-C2S-HELLO"
const NET_C2S_INPUT := &"NET-C2S-INPUT"
const NET_C2S_KILL := &"NET-C2S-KILL"
const NET_C2S_LOADOUT := &"NET-C2S-LOADOUT"
const NET_C2S_PING := &"NET-C2S-PING"
const NET_C2S_POSITION := &"NET-C2S-POSITION"
const NET_C2S_READY := &"NET-C2S-READY"
const NET_C2S_SCORE := &"NET-C2S-SCORE"
const NET_C2S_SKIP_RESULTS := &"NET-C2S-SKIP-RESULTS"
const NET_C2S_STUN := &"NET-C2S-STUN"
const NET_C2S_SUSPICION := &"NET-C2S-SUSPICION"
const NET_S2C_ABILITY_DENIED := &"NET-S2C-ABILITY-DENIED"
const NET_S2C_ABILITY_STARTED := &"NET-S2C-ABILITY-STARTED"
const NET_S2C_COMPASS := &"NET-S2C-COMPASS"
const NET_S2C_CONTRACT_ASSIGNED := &"NET-S2C-CONTRACT-ASSIGNED"
const NET_S2C_KILL_RESULT := &"NET-S2C-KILL-RESULT"
const NET_S2C_LOBBY_STATE := &"NET-S2C-LOBBY-STATE"
const NET_S2C_MATCH_END := &"NET-S2C-MATCH-END"
const NET_S2C_MATCH_START := &"NET-S2C-MATCH-START"
const NET_S2C_PHASE_CHANGED := &"NET-S2C-PHASE-CHANGED"
const NET_S2C_PLAYER_JOINED := &"NET-S2C-PLAYER-JOINED"
const NET_S2C_PONG := &"NET-S2C-PONG"
const NET_S2C_PREY_WARNING := &"NET-S2C-PREY-WARNING"
const NET_S2C_SCORE_EVENT := &"NET-S2C-SCORE-EVENT"
const NET_S2C_SNAPSHOT := &"NET-S2C-SNAPSHOT"
const NET_S2C_STUN_RESULT := &"NET-S2C-STUN-RESULT"
const NET_S2C_TUNING_SYNC := &"NET-S2C-TUNING-SYNC"
const NET_S2C_WELCOME := &"NET-S2C-WELCOME"

# --- SFX -----------------------------------------------------------------
## Sound effects.
const SFX_ABILITY_DENIED := &"SFX-ABILITY-DENIED"
const SFX_ABILITY_READY := &"SFX-ABILITY-READY"
const SFX_BLEND_BREAK := &"SFX-BLEND-BREAK"
const SFX_BLEND_ENTER := &"SFX-BLEND-ENTER"
const SFX_BLEND_EXIT := &"SFX-BLEND-EXIT"
const SFX_CINDERFALL_BURST := &"SFX-CINDERFALL-BURST"
const SFX_CINDERFALL_EXPIRE := &"SFX-CINDERFALL-EXPIRE"
const SFX_CINDERFALL_THROW := &"SFX-CINDERFALL-THROW"
const SFX_CLIMB_LOOP := &"SFX-CLIMB-LOOP"
const SFX_COMPASS_LOCK_BREAK := &"SFX-COMPASS-LOCK-BREAK"
const SFX_COMPASS_LOCK_COMPLETE := &"SFX-COMPASS-LOCK-COMPLETE"
const SFX_COMPASS_LOCK_FILL := &"SFX-COMPASS-LOCK-FILL"
const SFX_COMPASS_PULSE := &"SFX-COMPASS-PULSE"
const SFX_CONTRACT_ASSIGNED := &"SFX-CONTRACT-ASSIGNED"
const SFX_CORPSE_SPAWN := &"SFX-CORPSE-SPAWN"
const SFX_CROWD_GAWK_MURMUR := &"SFX-CROWD-GAWK-MURMUR"
const SFX_CROWD_STARTLE := &"SFX-CROWD-STARTLE"
const SFX_DEATH := &"SFX-DEATH"
const SFX_DROP_LAND_HARD := &"SFX-DROP-LAND-HARD"
const SFX_DROP_LAND_SOFT := &"SFX-DROP-LAND-SOFT"
const SFX_FOOTSTEP := &"SFX-FOOTSTEP"
const SFX_ID := &"SFX-ID"
const SFX_KILL_CONTACT := &"SFX-KILL-CONTACT"
const SFX_KILL_CONTEST_LOSS := &"SFX-KILL-CONTEST-LOSS"
const SFX_KILL_INITIATE := &"SFX-KILL-INITIATE"
const SFX_KILL_WHIFF := &"SFX-KILL-WHIFF"
const SFX_LUNGE_DASH := &"SFX-LUNGE-DASH"
const SFX_LUNGE_WHIFF := &"SFX-LUNGE-WHIFF"
const SFX_LUNGE_WINDUP := &"SFX-LUNGE-WINDUP"
const SFX_MANTLE := &"SFX-MANTLE"
const SFX_MATCH_COUNTDOWN := &"SFX-MATCH-COUNTDOWN"
const SFX_MATCH_END := &"SFX-MATCH-END"
const SFX_MATCH_FINALPHASE_START := &"SFX-MATCH-FINALPHASE-START"
const SFX_MATCH_FINALPHASE_WARN := &"SFX-MATCH-FINALPHASE-WARN"
const SFX_MATCH_START := &"SFX-MATCH-START"
const SFX_NPC_BUMP := &"SFX-NPC-BUMP"
const SFX_RESPAWN := &"SFX-RESPAWN"
const SFX_SCORE_BONUS_LARGE := &"SFX-SCORE-BONUS-LARGE"
const SFX_SCORE_BONUS_SMALL := &"SFX-SCORE-BONUS-SMALL"
const SFX_SCORE_PENALTY := &"SFX-SCORE-PENALTY"
const SFX_SECONDFACE_MORPH_IN := &"SFX-SECONDFACE-MORPH-IN"
const SFX_SECONDFACE_MORPH_OUT := &"SFX-SECONDFACE-MORPH-OUT"
const SFX_STUN_INITIATE := &"SFX-STUN-INITIATE"
const SFX_STUN_INVALID := &"SFX-STUN-INVALID"
const SFX_STUN_RECEIVED := &"SFX-STUN-RECEIVED"
const SFX_STUN_RECOVER := &"SFX-STUN-RECOVER"
const SFX_STUN_SUCCESS := &"SFX-STUN-SUCCESS"
const SFX_TIER_CLEARED := &"SFX-TIER-CLEARED"
const SFX_TIER_EXPOSED := &"SFX-TIER-EXPOSED"
const SFX_TIER_NOTICED := &"SFX-TIER-NOTICED"
const SFX_UI_BACK := &"SFX-UI-BACK"
const SFX_UI_CONFIRM := &"SFX-UI-CONFIRM"
const SFX_UI_NAV := &"SFX-UI-NAV"
const SFX_UI_READY := &"SFX-UI-READY"
const SFX_VAULT := &"SFX-VAULT"
const SFX_WARN_PREY_STING := &"SFX-WARN-PREY-STING"
const SFX_WHISPERBOLT_DRAW := &"SFX-WHISPERBOLT-DRAW"
const SFX_WHISPERBOLT_IMPACT := &"SFX-WHISPERBOLT-IMPACT"
const SFX_WHISPERBOLT_MISS := &"SFX-WHISPERBOLT-MISS"
const SFX_WHISPERBOLT_RELEASE := &"SFX-WHISPERBOLT-RELEASE"

# --- MUS -----------------------------------------------------------------
## Music stems.
const MUS_STEM_BASE := &"MUS-STEM-BASE"
const MUS_STEM_EXPOSED := &"MUS-STEM-EXPOSED"
const MUS_STEM_FINALPHASE := &"MUS-STEM-FINALPHASE"
const MUS_STEM_NOTICED := &"MUS-STEM-NOTICED"

# --- ANIM ----------------------------------------------------------------
## Animation clips.
const ANIM_BACKPEDAL_LOOP := &"ANIM-BACKPEDAL-LOOP"
const ANIM_BLEND_GROUP := &"ANIM-BLEND-GROUP"
const ANIM_BLEND_LEAN := &"ANIM-BLEND-LEAN"
const ANIM_BLEND_SIT := &"ANIM-BLEND-SIT"
const ANIM_BLEND_STAND := &"ANIM-BLEND-STAND"
const ANIM_BLENDWALK_LOOP := &"ANIM-BLENDWALK-LOOP"
const ANIM_BLENDWALK_START := &"ANIM-BLENDWALK-START"
const ANIM_BLENDWALK_STOP := &"ANIM-BLENDWALK-STOP"
const ANIM_BUMP_REACT := &"ANIM-BUMP-REACT"
const ANIM_CINDERFALL_THROW := &"ANIM-CINDERFALL-THROW"
const ANIM_CLIMB_LOOP := &"ANIM-CLIMB-LOOP"
const ANIM_CLIMB_MOUNT := &"ANIM-CLIMB-MOUNT"
const ANIM_CLIMB_TOP := &"ANIM-CLIMB-TOP"
const ANIM_DEATH := &"ANIM-DEATH"
const ANIM_DROP_FALL := &"ANIM-DROP-FALL"
const ANIM_DROP_LAND_HARD := &"ANIM-DROP-LAND-HARD"
const ANIM_DROP_LAND_SOFT := &"ANIM-DROP-LAND-SOFT"
const ANIM_GAWK := &"ANIM-GAWK"
const ANIM_IDLE_BASE := &"ANIM-IDLE-BASE"
const ANIM_IDLE_VAR_A := &"ANIM-IDLE-VAR-A"
const ANIM_IDLE_VAR_B := &"ANIM-IDLE-VAR-B"
const ANIM_IDLE_VAR_C := &"ANIM-IDLE-VAR-C"
const ANIM_JOG_LOOP := &"ANIM-JOG-LOOP"
const ANIM_KILL := &"ANIM-KILL"
const ANIM_KILL_VICTIM := &"ANIM-KILL-VICTIM"
const ANIM_KILL_WHIFF := &"ANIM-KILL-WHIFF"
const ANIM_LEDGE_GRAB := &"ANIM-LEDGE-GRAB"
const ANIM_LUNGE_DASH := &"ANIM-LUNGE-DASH"
const ANIM_LUNGE_WHIFF := &"ANIM-LUNGE-WHIFF"
const ANIM_LUNGE_WINDUP := &"ANIM-LUNGE-WINDUP"
const ANIM_MANTLE := &"ANIM-MANTLE"
const ANIM_RUN_LOOP := &"ANIM-RUN-LOOP"
const ANIM_SECONDFACE_MORPH_IN := &"ANIM-SECONDFACE-MORPH-IN"
const ANIM_SECONDFACE_MORPH_OUT := &"ANIM-SECONDFACE-MORPH-OUT"
const ANIM_SPRINT_LOOP := &"ANIM-SPRINT-LOOP"
const ANIM_STARTLE_FLEE := &"ANIM-STARTLE-FLEE"
const ANIM_STROLL_LOOP := &"ANIM-STROLL-LOOP"
const ANIM_STUN_DELIVER := &"ANIM-STUN-DELIVER"
const ANIM_STUN_INVALID := &"ANIM-STUN-INVALID"
const ANIM_STUN_RECEIVE := &"ANIM-STUN-RECEIVE"
const ANIM_TURN_L := &"ANIM-TURN-L"
const ANIM_TURN_R := &"ANIM-TURN-R"
const ANIM_VAULT := &"ANIM-VAULT"
const ANIM_WHISPERBOLT_RELEASE := &"ANIM-WHISPERBOLT-RELEASE"
const ANIM_WHISPERBOLT_WINDUP := &"ANIM-WHISPERBOLT-WINDUP"
