## Everything a system needs to know about a map, without loading its geometry.
##
## DATA_SCHEMA §4.3. `SYS-CROWD` reads the circuits and anchors, `SYS-SPAWN` the
## spawn points, `SYS-SUSPICION` the zones. None of them should have to walk a
## scene tree to find out where the map's affordances are — and the dedicated
## server needs all of this while excluding most of the geometry.
##
## GENERATED by tools/generate_map_vetraio.gd from the schematic in GDD-05 §2.
## Hand-editing it is silently reverted on the next run.
class_name MapData
extends Resource

@export var id: StringName = &""
@export var display_key: StringName = &""

## Playable extent. GDD-05 §2: ~120 x 120 m, three strata.
@export var bounds: AABB = AABB()

## TUN-SPAWN-POINT-COUNT of them — one per player at max lobby size, so a full
## simultaneous respawn is always satisfiable.
@export var spawn_points: Array[Vector3] = []

## TUN-CROWD-GROUP-COUNT closed loops of waypoints. Walking groups travel these.
@export var circuits: Array[PackedVector3Array] = []

## Seconds per lap, parallel to `circuits`. GDD-05 §2.5.
@export var circuit_periods: PackedFloat32Array = PackedFloat32Array()

## Where idle NPCs stand. Density comes from the zone each falls in.
@export var idle_anchors: Array[Vector3] = []

@export var zones: Array[MapZone] = []

## The five concealment props. TUN-BLEND-PROP-CAPACITY = 1 each.
@export var blend_props: Array[Vector3] = []

## Bench and stall-lean positions — the static prop blend, GDD-03 §4.1.3.
##
## **DERIVED FROM THE STALL TABLE, NEVER HAND-LISTED** (US-0054). Two lean spots
## per market stall, one on each long side, which is where a person actually
## stands to lean on a 0.9 m counter. Hand-listing them is the transcription that
## produced four unwalkable procession routes; a stall added later gets its lean
## spots without anybody remembering to add them.
@export var static_props: Array[Vector3] = []

## Stages where a chase is visible to an uninvolved third party. GDD-05 §5.
@export var theatre_spaces: Array[AABB] = []

## Surfaces NPCs must never reach: roofs, balconies, the canal. GDD-05 §4.4.
@export var navmesh_exclusions: Array[AABB] = []


func spawn_count() -> int:
	return spawn_points.size()


## Smallest distance between any two spawn points. GDD-05 §2.7 rule 1 requires
## 30 m: two players respawning simultaneously must not land in each other's
## kill range.
func min_spawn_separation() -> float:
	var smallest := INF
	for i: int in spawn_points.size():
		for j: int in range(i + 1, spawn_points.size()):
			smallest = minf(smallest, spawn_points[i].distance_to(spawn_points[j]))
	return 0.0 if smallest == INF else smallest


## The zone containing `point`, or null. Zones do not overlap.
func zone_at(point: Vector3) -> MapZone:
	for zone: MapZone in zones:
		if zone.bounds.has_point(point):
			return zone
	return null


## Anchors within `radius` of `point` — what TUN-BLEND-POCKET-MIN-NPC is counted
## against.
func anchors_near(point: Vector3, radius: float) -> int:
	var found := 0
	for anchor: Vector3 in idle_anchors:
		if anchor.distance_to(point) <= radius:
			found += 1
	return found
